TesteM.Web.MVC/Controllers/RelatorioServicoPrestadoController.cs
using System.Linq;
using System.Web.Mvc;
using TesteM.Application.Interfaces;
using TesteM.Application.ViewModels;

namespace TesteM.Web.MVC.Controllers
{
    public class RelatorioServicoPrestadoController : Controller
    {
        private readonly IServicoPrestadoAppService _servicoPrestadoAppService;

        public RelatorioServicoPrestadoController(IServicoPrestadoAppService servicoPrestadoAppService)
        {
            _servicoPrestadoAppService = servicoPrestadoAppService;
        }

        [Authorize]
        public PartialViewResult Pesquisar(FiltroRelatorioViewModel filtroRelatorioViewModel)
        {
            var servicoPrestadoViewModels = _servicoPrestadoAppService
                .ObterServicoPrestadoPorFiltro(filtroRelatorioViewModel).ToList();
            return PartialView("TabelaRelatorio", servicoPrestadoViewModels);
        }

        // GET: ServicoPrestadoViewModels
        [Authorize]
        public ActionResult Index()
        {
            var servicoPrestadoViewModels = _servicoPrestadoAppService.ObterServicoPrestados().ToList();
            return View("Index", servicoPrestadoViewModels);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarBairros() // its a GET, not a POST
        {
            var clientesViewModels =
                _servicoPrestadoAppService.ObterClientes().Select(x => new {x.Bairro}).Distinct().ToList();
            return Json(clientesViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarCidades() // its a GET, not a POST
        {
            var clientesViewModels =
                _servicoPrestadoAppService.ObterClientes().Select(x => new {x.Cidade}).Distinct().ToList();
            return Json(clientesViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarEstados() // its a GET, not a POST
        {
            var clientesViewModels =
                _servicoPrestadoAppService.ObterClientes().Select(x => new {x.Estado}).Distinct().ToList();
            return Json(clientesViewModels, JsonRequestBehavior.AllowGet);
        }
    }
}

TesteM.Web.MVC/Controllers/ServicoPrestadoController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using TesteM.Application.Interfaces;
using TesteM.Application.ViewModels;

namespace TesteM.Web.MVC.Controllers
{
    public class ServicoPrestadoController : Controller
    {
        private readonly IServicoPrestadoAppService _servicoPrestadoAppService;

        public ServicoPrestadoController(IServicoPrestadoAppService servicoPrestadoAppService)
        {
            _servicoPrestadoAppService = servicoPrestadoAppService;
        }

        // GET: ServicoPrestadoViewModels
        [Authorize]
        public ActionResult Index()
        {
            var servicoPrestadoViewModels = _servicoPrestadoAppService.ObterServicoPrestados().ToList();
            return View("Index", servicoPrestadoViewModels);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarFornecedores() // its a GET, not a POST
        {
            var fornecedorViewModels = _servicoPrestadoAppService.ObterFornecedores().ToList();
            return Json(fornecedorViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarClientes() // its a GET, not a POST
        {
            var clientesViewModels =
                _servicoPrestadoAppService.ObterClientes().Select(x => new {x.Id, x.Nome}).ToList();
            return Json(clientesViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpGet]
        public JsonResult ListarTiposServicos() // its a GET, not a POST
        {
            var tiposServicosViewModels =
                _servicoPrestadoAppService.ObterTiposServicos().Select(x => new {x.Id, x.Tipo}).ToList();
            return Json(tiposServicosViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public JsonResult InserirServicoPrestado(string descricaoServico, DateTime dataAtendimento,
            decimal valorServico, int clienteId, int fornecedorId, int tipoServicoId) // its a GET, not a POST
        {
            var servicoPrestadoViewModel =
                new ServicoPrestadoViewModel
                {
                    DescricaoServico = descricaoServico,
                    DataAtendimento = dataAtendimento,
                    ValorServico = valorServico,
                    ClienteId = clienteId,
                    FornecedorId = fornecedorId,
                    TipoServicoId = tipoServicoId
                };


            var tiposServicosViewModels = _servicoPrestadoAppService.InserirServicoPrestado(servicoPrestadoViewModel);
            return Json(tiposServicosViewModels, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public JsonResult RemoverServicoPrestado(int id) // its a GET, not a POST
        {
            return Json(_servicoPrestadoAppService.RemoverServicoPrestado(id), JsonRequestBehavior.AllowGet);
        }
    }
}

TesteM.Web.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/toastr.css" rel="stylesheet"/>
    <link href="~/Content/toastr.min.css" rel="stylesheet"/>
    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet"/>
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet"/>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.flash.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.flash.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.print.min.js"></script>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Teste M", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})*@
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Quadro de Informações", "Index", "Home")</li>
                <li>@Html.ActionLink("Cadastrar Serviços", "Index", "ServicoPrestado")</li>
                <li>@Html.ActionLink("Relatório de Serviços", "Index", "RelatorioServicoPrestado")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>